sonar.projectKey=usamaio_smart-property-maintenance-cicd
sonar.organization=usamaio

sonar.sources=apps,spm_platform
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/migrations/**,**/__pycache__/**,htmlcov/**,static/**,media/**,venv/**
sonar.coverage.exclusions=**/tests/**,**/migrations/**,manage.py