# Generated by Django 5.2.7 on 2026-07-10 02:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('appliance_type', models.CharField(choices=[('boiler', 'Boiler'), ('washing_machine', 'Washing Machine'), ('dishwasher', 'Dishwasher'), ('refrigerator', 'Refrigerator'), ('freezer', 'Freezer'), ('oven', 'Oven'), ('microwave', 'Microwave'), ('heating_system', 'Heating System'), ('air_conditioner', 'Air Conditioner'), ('smoke_alarm', 'Smoke Alarm'), ('other', 'Other')], default='other', max_length=30)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service'), ('retired', 'Retired')], default='active', max_length=30)),
                ('has_individual_qr', models.BooleanField(default=False, help_text='Enable this for high-value or frequently serviced appliances.')),
                ('appliance_qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='properties.property')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appliances', to='properties.room')),
            ],
            options={
                'verbose_name': 'Appliance',
                'verbose_name_plural': 'Appliances',
                'ordering': ['name'],
            },
        ),
    ]
