# Generated by Django 5.2.7 on 2026-08-03 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0002_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='appliance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='appliances.appliance'),
        ),
    ]
