# Generated by Django 5.2.7 on 2026-08-05 01:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0003_alter_warranty_appliance'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_date', models.DateField()),
                ('service_provider', models.CharField(max_length=150)),
                ('technician_name', models.CharField(blank=True, max_length=150)),
                ('work_performed', models.TextField()),
                ('parts_replaced', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='appliances.appliance')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records_created', to=settings.AUTH_USER_MODEL)),
                ('maintenance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='maintenance.maintenancerequest')),
            ],
            options={
                'verbose_name': 'Service Record',
                'verbose_name_plural': 'Service Records',
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
